services:
  api:
    container_name: api
    image: emilento/sampleapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__Using__1=Serilog.Sinks.Seq
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
      - ConnectionStrings__SampleDbContext=Data Source=database;Initial Catalog=docker-workshops;User Id=sa;Password=HappyTeam@2022;
    depends_on:
      - seq
      - database

  seq:
    container_name: seq
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5340:80
      - 5341:5341
    volumes:
      - seq_data:/data

  database:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HappyTeam@2022
    ports:
      - 1433:1433
    volumes:
      - .docker/mssql/data:/var/opt/mssql/data

volumes:
  seq_data: {}